name: 'Setup Dependencies & Run Tests'
description: 'Install the nessesary dependencies and run the tests in this repo'
inputs:
  version-python:
    required: true

  # One could also set multiple libraries to be tested in one workflow
  version-pytorch:
    required: false

  # We cannot access the secrets in the composite action, so we have to pass it as an input
  codecov-token:
    required: true

runs:
  using: 'composite'
  steps:
    # - name: Set up Python ${{ matrix.version-python }}
    #   uses: actions/setup-python@v5
    #   with:
    #     python-version: ${{ matrix.version-python }}
    #     cache: 'pip' # caching pip dependencies
    #     cache-dependency-path: |
    #       **/pyproject.toml
    - name: Install uv and set up Python
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.9.6"
        enable-cache: true
        python-version: ${{ matrix.version-python }}


    - name: Install library and dependencies
      shell: bash
      run: |
        uv venv --python ${{ matrix.version-python }} && uv sync --extra dev

    - name: Set up Torch ${{ matrix.version-pytorch }}
      if: matrix.version-pytorch
      shell: bash
      run: |
        uv pip install torch==${{ matrix.version-pytorch }} 

    - name: Test with pytest
      shell: bash
      run: |
        uv run pytest --cov=spflow --cov-branch

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ matrix.codecov-token }}
