from .bernoulli import sample
from .binomial import sample
from .exponential import sample
from .gamma import sample
from .gaussian import sample
from .geometric import sample
from .hypergeometric import sample
from .log_normal import sample
from .multivariate_gaussian import sample
from .negative_binomial import sample
from .poisson import sample
from .uniform import sample
