@startuml
abstract class Module

abstract class NestingModule {
  placeholders : List[Placeholder]
  ---
  create_placeholder(...)
  set_placeholders(...)
}

class Placeholder {
  input_ids
  owner
}

Module <|-- NestingModule
Module <|-- Placeholder
NestingModule +-- Placeholder
NestingModule --> Placeholder

@enduml